[package]
name = "libp2p-secio"
version = "0.1.0"
authors = ["Wim Looman <wim@nemo157.com>"]

[dependencies]
libp2p-identity = { path = "../libp2p-identity" }
msgio = { path = "../msgio" }
protobuf = "*"
ring = { git = "https://github.com/briansmith/ring" }
