[package]
name = "libp2p-secio"
version = "0.1.0"
authors = ["Wim Looman <wim@nemo157.com>"]

[dependencies]
libp2p-identity = { path = "../libp2p-identity" }
msgio = { path = "../msgio" }
protobuf = "*"
ring = "0.5.3"
untrusted = "0.3.1"
rust-crypto = "0.2.36"
mhash = "0.1.1"
