[package]
name = "libp2p-secio"
version = "0.1.0"
authors = ["Wim Looman <wim@nemo157.com>"]

[dependencies]
libp2p-identity = { path = "../libp2p-identity-rs" }
protobuf = "*"
ring = "0.5.3"
untrusted = "0.3.1"
rust-crypto = "0.2.36"
mhash = { version = "0.2.0", features = ["generation", "sha2"] }
futures = "*"
tokio-core = "*"
